module.exports = {
  apps: [
    {
      name: 'ralph-analytics',
      script: './ralph-analytics/api/server.js',
      cwd:    '/home/1638322.cloudwaysapps.com/amxhnzbwdx/public_html/monorepo',
      env: {
        NODE_ENV:       'production',
        PORT:           '3000',
        DB_HOST:        '127.0.0.1',
        DB_PORT:        '3306',
        DB_NAME:        'amxhnzbwdx',
        DB_USER:        'amxhnzbwdx',
        DB_PASS: 'fw8cvQ4hDH',
        REDIS_URL:      'redis://amxhnzbwdx:BECEuUev5w@127.0.0.1:6379',
        REDIS_PASSWORD: 'BECEuUev5w',
        JWT_SECRET: '',
        RESEND_API_KEY: '',
        SMTP_HOST:      'smtp.resend.com',
        SMTP_PORT:      '465',
        SMTP_USER:      'resend',
        SMTP_PASS: 're_ecxTHmor_AKSwQa36A2zBCtUbBs5P5EV3',
        SMTP_FROM:      'noreply@ralph-analytics.com',
        SMTP_SECURE:    'true',
        REDIS_USER:     'amxhnzbwdx',
      },
    },
    {
      name: 'ralph-orchestrator',
      script: './ralph-analytics/apps/ralph-orchestrator/src/index.js',
      cwd:    '/home/1638322.cloudwaysapps.com/amxhnzbwdx/public_html/monorepo',
      env: { NODE_ENV: 'production', PORT: '4020' },
    },
    {
      name: 'ralph-ai',
      script: './ralph-analytics/apps/ai-service/src/index.js',
      cwd:    '/home/1638322.cloudwaysapps.com/amxhnzbwdx/public_html/monorepo',
      env: { NODE_ENV: 'production', PORT: '4001', OPENAI_API_KEY: process.env.OPENAI_API_KEY },
    },
    {
      name: 'ralph-messaging',
      script: './ralph-analytics/apps/messaging-service/src/index.js',
      cwd:    '/home/1638322.cloudwaysapps.com/amxhnzbwdx/public_html/monorepo',
      env: { NODE_ENV: 'production', PORT: '4002' },
    },
    {
      name: 'ralph-irmp',
      script: './ralph-analytics/packages/irmp/index.js',
      cwd:    '/home/1638322.cloudwaysapps.com/amxhnzbwdx/public_html/monorepo',
      env: { NODE_ENV: 'production', PORT: '3040' },
    },
    {
      name: 'ralph-scvms',
      script: './ralph-analytics/packages/scvms/index.js',
      cwd:    '/home/1638322.cloudwaysapps.com/amxhnzbwdx/public_html/monorepo',
      env: { NODE_ENV: 'production', PORT: '3050' },
    },
    {
      name: 'ralph-rcars',
      script: './ralph-analytics/packages/rcars/index.js',
      cwd:    '/home/1638322.cloudwaysapps.com/amxhnzbwdx/public_html/monorepo',
      env: { NODE_ENV: 'production', PORT: '3060' },
    },
    {
      name: 'ralph-capts',
      script: './ralph-analytics/packages/capts/index.js',
      cwd:    '/home/1638322.cloudwaysapps.com/amxhnzbwdx/public_html/monorepo',
      env: { NODE_ENV: 'production', PORT: '3070' },
    },
    {
      name: 'ralph-iarfs',
      script: './ralph-analytics/packages/iarfs/index.js',
      cwd:    '/home/1638322.cloudwaysapps.com/amxhnzbwdx/public_html/monorepo',
      env: { NODE_ENV: 'production', PORT: '3080' },
    },
    {
      name: 'ralph-cid',
      script: './ralph-analytics/packages/cid/index.js',
      cwd:    '/home/1638322.cloudwaysapps.com/amxhnzbwdx/public_html/monorepo',
      env: { NODE_ENV: 'production', PORT: '3090' },
    },
    {
      name: 'ralph-gres',
      script: './ralph-analytics/packages/gres/index.js',
      cwd:    '/home/1638322.cloudwaysapps.com/amxhnzbwdx/public_html/monorepo',
      env: { NODE_ENV: 'production', PORT: '3100' },
    },
      {
      name: 'ralph-te-vetting',
      script: './ralph-analytics/packages/te-vetting/index.js',
      cwd:    '/home/1638322.cloudwaysapps.com/amxhnzbwdx/public_html/monorepo',
      env: { NODE_ENV: 'production', PORT: '3120' },
    },
  ],
};